name: Deploy to Amazon EC2

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: ingda-gitaction-s3-bucket
  CODE_DEPLOY_APPLICATION_NAME: ingda-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: ingda-codedeploy-deployment-group

permissions:
  contents: read

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Copy Secret1
        env:
          OCCUPY_SECRET1: ${{ secrets.DB_INFO_SECRET }}
          OCCUPY_SECRET1_DIR: src/main/resources
          OCCUPY_SECRET1_DIR_FILE_NAME: application-db.properties
        run: echo $OCCUPY_SECRET1

      - name: Copy Secret2
        env:
          OCCUPY_SECRET2: ${{ secrets.EMAIL_SERVICE_SECRET }}
          OCCUPY_SECRET2_DIR: src/main/resources
          OCCUPY_SECRET2_DIR_FILE_NAME: application-email.properties
        run: echo $OCCUPY_SECRET2

      - name: Copy Secret3
        env:
          OCCUPY_SECRET2: ${{ secrets.SECURITY_SECRET }}
          OCCUPY_SECRET2_DIR: src/main/resources
          OCCUPY_SECRET2_DIR_FILE_NAME: application-jwt.properties
        run: echo $OCCUPY_SECRET3


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source .
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip